DROP TABLE IF EXISTS movies;
CREATE TABLE IF NOT EXISTS movies (
   movie_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   title VARCHAR(100) NOT NULL,
   year_released INTEGER NOT NULL,
   director VARCHAR(80) NOT NULL,
   color VARCHAR(10) NOT NULL
);
CREATE TABLE directors (
   director_id INTEGER PRIMARY KEY AUTO_INCREMENT,
   first_name VARCHAR(40),
   last_name VARCHAR(40),
   country VARCHAR(80)
);